import type { Book, Review, User, Library, Badge } from "../types"

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Ana Luiza Costa',
    username: 'analuiza',
    email: 'ana@biblioverse.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana&backgroundColor=b6e3f4',
    bio: 'Apaixonada por clássicos e ficção científica. Leitora compulsiva desde os 8 anos.',
    profession: 'Escritora',
    city: 'São Paulo',
    booksRead: 127,
    followers: 2341,
    following: 189,
    createdAt: '2023-01-15',
    readingStreak: 47,
    currentGoal: { target: 52, current: 38, year: 2025 },
  },
  {
    id: '2',
    name: 'Rafael Mendes',
    username: 'rafamendes',
    email: 'rafa@biblioverse.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rafael&backgroundColor=c0aede',
    bio: 'Filosofia, história e um bom café. Leitor noturno por excelência.',
    profession: 'Professor',
    city: 'Rio de Janeiro',
    booksRead: 89,
    followers: 1204,
    following: 302,
    createdAt: '2023-03-20',
    readingStreak: 12,
    currentGoal: { target: 40, current: 28, year: 2025 },
  },
  {
    id: '3',
    name: 'Marina Oliveira',
    username: 'marinaoliveira',
    email: 'marina@biblioverse.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marina&backgroundColor=ffd5dc',
    bio: 'Fantasy lover. Cada livro é um portal para outro mundo.',
    profession: 'Designer',
    city: 'Curitiba',
    booksRead: 213,
    followers: 5678,
    following: 421,
    createdAt: '2022-11-05',
    readingStreak: 89,
    currentGoal: { target: 60, current: 51, year: 2025 },
  },
]

export const CURRENT_USER: User = {
  id: '1',
  name: 'Ana Luiza Costa',
  username: 'analuiza',
  email: 'ana@biblioverse.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana&backgroundColor=b6e3f4',
  bio: 'Apaixonada por clássicos e ficção científica. Leitora compulsiva desde os 8 anos.',
  profession: 'Escritora',
  city: 'São Paulo',
  booksRead: 127,
  followers: 2341,
  following: 189,
  createdAt: '2023-01-15',
  readingStreak: 47,
  currentGoal: { target: 52, current: 38, year: 2025 },
}

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'O Nome do Vento',
    author: 'Patrick Rothfuss',
    cover: 'https://covers.openlibrary.org/b/id/8387576-L.jpg',
    genre: 'Fantasia',
    description: 'A história de Kvothe, um músico lendário, assassino de reis e mago, contada em suas próprias palavras.',
    rating: 4.8,
    reviewCount: 2341,
    publishedAt: 2007,
    pages: 662,
    trending: true,
    tags: ['épico', 'magia', 'aventura'],
  },
  {
    id: '2',
    title: 'Duna',
    author: 'Frank Herbert',
    cover: 'https://covers.openlibrary.org/b/id/8225267-L.jpg',
    genre: 'Ficção Científica',
    description: 'Em um futuro distante, o jovem Paul Atreides chega ao planeta deserto Arrakis, a única fonte da especiaria mais valiosa do universo.',
    rating: 4.9,
    reviewCount: 5621,
    publishedAt: 1965,
    pages: 896,
    trending: true,
    tags: ['clássico', 'política', 'ecologia'],
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    cover: 'https://covers.openlibrary.org/b/id/8575708-L.jpg',
    genre: 'Ficção Científica',
    description: 'Em um futuro distópico, Winston Smith vive em um mundo totalitário onde cada movimento é monitorado pelo Grande Irmão.',
    rating: 4.7,
    reviewCount: 8923,
    publishedAt: 1949,
    pages: 328,
    trending: false,
    tags: ['distopia', 'clássico', 'política'],
  },
  {
    id: '4',
    title: 'O Senhor dos Anéis',
    author: 'J.R.R. Tolkien',
    cover: 'https://covers.openlibrary.org/b/id/8406786-L.jpg',
    genre: 'Fantasia',
    description: 'A épica jornada de Frodo Baggins para destruir o Um Anel e salvar a Terra-média do Senhor das Trevas Sauron.',
    rating: 4.9,
    reviewCount: 12045,
    publishedAt: 1954,
    pages: 1216,
    trending: true,
    tags: ['épico', 'clássico', 'aventura'],
  },
  {
    id: '5',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    cover: 'https://covers.openlibrary.org/b/id/8286715-L.jpg',
    genre: 'História',
    description: 'Uma breve história da humanidade, desde a Revolução Cognitiva até os dias atuais.',
    rating: 4.6,
    reviewCount: 7823,
    publishedAt: 2011,
    pages: 464,
    trending: true,
    tags: ['não-ficção', 'história', 'evolução'],
  },
  {
    id: '6',
    title: 'O Pequeno Príncipe',
    author: 'Antoine de Saint-Exupéry',
    cover: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    genre: 'Clássicos',
    description: 'Um clássico da literatura mundial que narra a história de um pequeno príncipe que viaja pelo universo.',
    rating: 4.8,
    reviewCount: 15234,
    publishedAt: 1943,
    pages: 96,
    trending: false,
    tags: ['clássico', 'poético', 'filosófico'],
  },
  {
    id: '7',
    title: 'Atomic Habits',
    author: 'James Clear',
    cover: 'https://covers.openlibrary.org/b/id/10522757-L.jpg',
    genre: 'Desenvolvimento Pessoal',
    description: 'Um guia prático e comprovado para construir bons hábitos e quebrar os maus.',
    rating: 4.7,
    reviewCount: 9456,
    publishedAt: 2018,
    pages: 320,
    trending: true,
    tags: ['produtividade', 'hábitos', 'psicologia'],
  },
  {
    id: '8',
    title: 'Cem Anos de Solidão',
    author: 'Gabriel García Márquez',
    cover: 'https://covers.openlibrary.org/b/id/8234577-L.jpg',
    genre: 'Drama',
    description: 'A saga da família Buendía ao longo de sete gerações na cidade fictícia de Macondo.',
    rating: 4.6,
    reviewCount: 6789,
    publishedAt: 1967,
    pages: 417,
    trending: false,
    tags: ['realismo mágico', 'clássico', 'família'],
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    content: 'Uma obra-prima absoluta. Rothfuss constrói um mundo tão rico e detalhado que é impossível não se perder completamente. A prosa é simplesmente bela — poética sem ser pomposa. Kvothe é um protagonista fascinante, cheio de contradições. Cada página é um prazer.',
    rating: 5,
    createdAt: '2025-05-08T14:30:00Z',
    likes: 234,
    comments: 18,
    liked: false,
    saved: false,
    user: MOCK_USERS[0],
    book: MOCK_BOOKS[0],
  },
  {
    id: '2',
    content: 'Duna é simplesmente genial. Herbert criou um universo complexo, político e ecológico que parece completamente real. A mensagem sobre dependência de recursos naturais nunca foi tão atual. Uma leitura obrigatória para qualquer fã de ficção científica.',
    rating: 5,
    createdAt: '2025-05-07T09:15:00Z',
    likes: 456,
    comments: 32,
    liked: true,
    saved: true,
    user: MOCK_USERS[1],
    book: MOCK_BOOKS[1],
  },
  {
    id: '3',
    content: 'Reli pela terceira vez e ainda me impressiona como Orwell foi tão profético. A linguagem simples mas poderosa torna cada distopia descrita visceralmente real. "A guerra é paz. A liberdade é escravidão. A ignorância é força." — assustadoramente atual.',
    rating: 5,
    createdAt: '2025-05-06T20:45:00Z',
    likes: 312,
    comments: 27,
    liked: false,
    saved: false,
    user: MOCK_USERS[2],
    book: MOCK_BOOKS[2],
  },
  {
    id: '4',
    content: 'Atomic Habits mudou completamente minha perspectiva sobre produtividade. James Clear explica de forma clara e prática como pequenas mudanças se acumulam em resultados extraordinários. Já aplico os conceitos há 3 meses e a diferença é notável.',
    rating: 4,
    createdAt: '2025-05-05T11:20:00Z',
    likes: 189,
    comments: 14,
    liked: true,
    saved: false,
    user: MOCK_USERS[0],
    book: MOCK_BOOKS[6],
  },
  {
    id: '5',
    content: 'García Márquez escreve como quem pinta com palavras. Cem Anos de Solidão é uma experiência literária única — o realismo mágico flui de forma tão natural que você aceita completamente o impossível como parte do cotidiano.',
    rating: 5,
    createdAt: '2025-05-04T16:00:00Z',
    likes: 278,
    comments: 21,
    liked: false,
    saved: true,
    user: MOCK_USERS[1],
    book: MOCK_BOOKS[7],
  },
]

export const MOCK_LIBRARIES: Library[] = [
  {
    id: '1',
    name: 'Biblioteca Mário de Andrade',
    address: 'Rua da Consolação, 94 - Centro',
    city: 'São Paulo',
    phone: '(11) 3775-0031',
    website: 'https://www.prefeitura.sp.gov.br/bibliotecas',
    hours: 'Seg-Sex: 8h-20h | Sáb: 9h-17h',
    lat: -23.5489,
    lng: -46.6388,
    rating: 4.7,
  },
  {
    id: '2',
    name: 'Biblioteca Parque Villa-Lobos',
    address: 'Av. Professor Fonseca Rodrigues, 1384 - Alto de Pinheiros',
    city: 'São Paulo',
    phone: '(11) 3779-6600',
    website: 'https://www.bibliotecasvilla-lobos.org.br',
    hours: 'Seg-Sex: 9h-21h | Sáb-Dom: 10h-18h',
    lat: -23.5418,
    lng: -46.7168,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Biblioteca Nacional',
    address: 'Av. Rio Branco, 219 - Centro',
    city: 'Rio de Janeiro',
    phone: '(21) 3095-3879',
    website: 'https://www.bn.gov.br',
    hours: 'Seg-Sex: 9h-20h | Sáb: 9h-15h',
    lat: -22.9065,
    lng: -43.1753,
    rating: 4.8,
  },
]

export const MOCK_BADGES: Badge[] = [
  { id: '1', name: 'Devorador', icon: '📚', description: 'Leu 100 livros', earnedAt: '2024-12-01' },
  { id: '2', name: 'Crítico', icon: '⭐', description: 'Escreveu 50 reviews', earnedAt: '2024-10-15' },
  { id: '3', name: 'Social', icon: '🤝', description: 'Conquistou 1000 seguidores' },
  { id: '4', name: 'Maratonista', icon: '🔥', description: 'Streak de 30 dias', earnedAt: '2025-02-14' },
  { id: '5', name: 'Explorador', icon: '🗺️', description: 'Leu 10 gêneros diferentes', earnedAt: '2024-08-20' },
  { id: '6', name: 'Influencer', icon: '✨', description: 'Review com 500 curtidas' },
]

export const GENRES = [
  { name: 'Romance', icon: '💕', color: 'from-pink-500 to-rose-500', count: 1243 },
  { name: 'Fantasia', icon: '🧙', color: 'from-violet-500 to-purple-600', count: 987 },
  { name: 'Ficção Científica', icon: '🚀', color: 'from-blue-500 to-cyan-500', count: 756 },
  { name: 'Terror', icon: '👻', color: 'from-gray-600 to-gray-900', count: 534 },
  { name: 'Filosofia', icon: '🤔', color: 'from-amber-500 to-orange-500', count: 423 },
  { name: 'Negócios', icon: '💼', color: 'from-green-500 to-emerald-600', count: 612 },
  { name: 'Desenvolvimento Pessoal', icon: '🌱', color: 'from-teal-500 to-green-500', count: 789 },
  { name: 'Tecnologia', icon: '💻', color: 'from-sky-500 to-blue-600', count: 345 },
  { name: 'HQs', icon: '💥', color: 'from-yellow-400 to-orange-500', count: 456 },
  { name: 'Mangás', icon: '⛩️', color: 'from-red-500 to-pink-500', count: 678 },
  { name: 'História', icon: '📜', color: 'from-stone-500 to-amber-600', count: 534 },
  { name: 'Drama', icon: '🎭', color: 'from-indigo-500 to-violet-500', count: 321 },
  { name: 'Clássicos', icon: '🏛️', color: 'from-yellow-500 to-amber-500', count: 897 },
  { name: 'Suspense', icon: '🔍', color: 'from-slate-600 to-gray-700', count: 567 },
]

export const STATS = [
  { label: 'Leitores Ativos', value: '47.293', suffix: '+' },
  { label: 'Livros Catalogados', value: '128.451', suffix: '+' },
  { label: 'Reviews Publicadas', value: '892.634', suffix: '+' },
  { label: 'Bibliotecas Mapeadas', value: '2.341', suffix: '+' },
]
